[package]
name = "finn-kernel"
version = "0.0.1"
edition.workspace = true
license.workspace = true
publish = false
description = "The core kernel crate for FinnOS."

[lib]
path = "src/lib.rs"

[dependencies]
finn-boot-protocol = { path = "../boot/protocol" }

[features]
default = []
kernel-bin = []
qemu-test-exit = []
qemu-test-panic = []
qemu-test-exceptions = []
qemu-test-memory-map = []
qemu-test-page-allocator = []
qemu-test-page-tables = ["qemu-test-exit"]
qemu-test-heap = ["qemu-test-exit"]
qemu-test-timer-interrupts = ["qemu-test-exit"]

[[bin]]
name = "finn-kernel-x86_64"
path = "src/bin/x86_64.rs"
required-features = ["kernel-bin"]
test = false
bench = false

[build-dependencies]
finn-boot-protocol = { path = "../boot/protocol" }

[lints]
workspace = true
