//! FinnOS x86-64 exception dispatch and handlers.

use core::sync::atomic::{AtomicU8, Ordering};

use super::idt::{self, IDT_INTERRUPT_GATE, IDT_TRAP_GATE};
use super::qemu;
use super::serial;
use super::tss::TSS;

/// Exception vector for the breakpoint instruction (`int3`).
pub const VECTOR_BREAKPOINT: u8 = 3;
/// Exception vector for invalid opcode (`ud2`).
pub const VECTOR_INVALID_OPCODE: u8 = 6;
/// Exception vector for double fault.
pub const VECTOR_DOUBLE_FAULT: u8 = 8;
/// Exception vector for general-protection fault.
pub const VECTOR_GENERAL_PROTECTION: u8 = 13;
/// Exception vector for page fault.
pub const VECTOR_PAGE_FAULT: u8 = 14;

/// Vectors that carry a hardware error code.
pub const ERROR_CODE_VECTORS: &[u8] = &[8, 10, 11, 12, 13, 14, 17, 30];

/// Atomic test state for the controlled exception test feature.
static TEST_STATE: AtomicU8 = AtomicU8::new(TestState::Idle as u8);

/// Permanently resident Task State Segment used by the early exception foundation.
static mut EXCEPTION_TSS: TSS = TSS::new();

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
enum TestState {
    /// No exception test is in progress.
    Idle = 0,
    /// A breakpoint test is in progress.
    Breakpoint = 1,
    /// An invalid-opcode test is in progress.
    InvalidOpcode = 2,
}

/// Normalized exception frame built by the assembly entry stubs.
///
/// The assembly stub pushes the general-purpose registers in the order shown below, then the
/// vector, then a synthetic or hardware error code, followed by the CPU-pushed `rip`, `cs`, and
/// `rflags`. This layout must exactly match the assembly push order.
///
/// Note: because the kernel currently runs only in ring 0, the CPU does not push `rsp` and `ss`
/// for these exceptions. The assembly stubs and this structure are valid only for ring-0
/// exceptions; a future ring-3 path will need to account for the additional hardware frame.
#[repr(C)]
#[allow(missing_docs)]
pub struct ExceptionFrame {
    /// General-purpose registers, pushed in order from `rax` up to `r15`.
    pub rax: u64,
    pub rbx: u64,
    pub rcx: u64,
    pub rdx: u64,
    pub rsi: u64,
    pub rdi: u64,
    pub rbp: u64,
    pub r8: u64,
    pub r9: u64,
    pub r10: u64,
    pub r11: u64,
    pub r12: u64,
    pub r13: u64,
    pub r14: u64,
    pub r15: u64,
    /// Exception vector number.
    pub vector: u64,
    /// Hardware error code, or a synthetic zero for exceptions without one.
    pub error_code: u64,
    /// Instruction pointer pushed by the CPU.
    pub rip: u64,
    /// Code segment pushed by the CPU.
    pub cs: u64,
    /// RFLAGS pushed by the CPU.
    pub rflags: u64,
}

/// Assert that the frame layout matches the assembly push order.
#[allow(dead_code)]
const fn _assert_frame_layout() {
    use core::mem::offset_of;
    let _ = offset_of!(ExceptionFrame, rax);
    let _ = offset_of!(ExceptionFrame, vector);
    let _ = offset_of!(ExceptionFrame, error_code);
    let _ = offset_of!(ExceptionFrame, rip);
}

// Assembly entry stubs generated by `global_asm!`.
core::arch::global_asm!(
    r#"
    .macro SAVE_REGS
        push r15
        push r14
        push r13
        push r12
        push r11
        push r10
        push r9
        push r8
        push rbp
        push rdi
        push rsi
        push rdx
        push rcx
        push rbx
        push rax
    .endm

    .macro RESTORE_REGS
        pop rax
        pop rbx
        pop rcx
        pop rdx
        pop rsi
        pop rdi
        pop rbp
        pop r8
        pop r9
        pop r10
        pop r11
        pop r12
        pop r13
        pop r14
        pop r15
    .endm

    .align 16
    .globl exception_no_error
    exception_no_error:
        SAVE_REGS
        mov rdi, rsp
        call rust_exception_dispatch
        RESTORE_REGS
        add rsp, 16
        iretq

    .align 16
    .globl exception_error
    exception_error:
        SAVE_REGS
        mov rdi, rsp
        call rust_exception_dispatch
        RESTORE_REGS
        add rsp, 8
        iretq

    .align 16
    .globl vector_0
    vector_0:
        push 0
        push 0
        jmp exception_no_error
    .align 16
    .globl vector_1
    vector_1:
        push 0
        push 1
        jmp exception_no_error
    .align 16
    .globl vector_2
    vector_2:
        push 0
        push 2
        jmp exception_no_error
    .align 16
    .globl vector_3
    vector_3:
        push 0
        push 3
        jmp exception_no_error
    .align 16
    .globl vector_4
    vector_4:
        push 0
        push 4
        jmp exception_no_error
    .align 16
    .globl vector_5
    vector_5:
        push 0
        push 5
        jmp exception_no_error
    .align 16
    .globl vector_6
    vector_6:
        push 0
        push 6
        jmp exception_no_error
    .align 16
    .globl vector_7
    vector_7:
        push 0
        push 7
        jmp exception_no_error
    .align 16
    .globl vector_8
    vector_8:
        push 8
        jmp exception_error
    .align 16
    .globl vector_9
    vector_9:
        push 0
        push 9
        jmp exception_no_error
    .align 16
    .globl vector_10
    vector_10:
        push 10
        jmp exception_error
    .align 16
    .globl vector_11
    vector_11:
        push 11
        jmp exception_error
    .align 16
    .globl vector_12
    vector_12:
        push 12
        jmp exception_error
    .align 16
    .globl vector_13
    vector_13:
        push 13
        jmp exception_error
    .align 16
    .globl vector_14
    vector_14:
        push 14
        jmp exception_error
    .align 16
    .globl vector_15
    vector_15:
        push 0
        push 15
        jmp exception_no_error
    .align 16
    .globl vector_16
    vector_16:
        push 0
        push 16
        jmp exception_no_error
    .align 16
    .globl vector_17
    vector_17:
        push 17
        jmp exception_error
    .align 16
    .globl vector_18
    vector_18:
        push 0
        push 18
        jmp exception_no_error
    .align 16
    .globl vector_19
    vector_19:
        push 0
        push 19
        jmp exception_no_error
    .align 16
    .globl vector_20
    vector_20:
        push 0
        push 20
        jmp exception_no_error
    .align 16
    .globl vector_21
    vector_21:
        push 0
        push 21
        jmp exception_no_error
    .align 16
    .globl vector_22
    vector_22:
        push 0
        push 22
        jmp exception_no_error
    .align 16
    .globl vector_23
    vector_23:
        push 0
        push 23
        jmp exception_no_error
    .align 16
    .globl vector_24
    vector_24:
        push 0
        push 24
        jmp exception_no_error
    .align 16
    .globl vector_25
    vector_25:
        push 0
        push 25
        jmp exception_no_error
    .align 16
    .globl vector_26
    vector_26:
        push 0
        push 26
        jmp exception_no_error
    .align 16
    .globl vector_27
    vector_27:
        push 0
        push 27
        jmp exception_no_error
    .align 16
    .globl vector_28
    vector_28:
        push 0
        push 28
        jmp exception_no_error
    .align 16
    .globl vector_29
    vector_29:
        push 0
        push 29
        jmp exception_no_error
    .align 16
    .globl vector_30
    vector_30:
        push 30
        jmp exception_error
    .align 16
    .globl vector_31
    vector_31:
        push 0
        push 31
        jmp exception_no_error
    "#
);

unsafe extern "C" {
    fn vector_0();
    fn vector_1();
    fn vector_2();
    fn vector_3();
    fn vector_4();
    fn vector_5();
    fn vector_6();
    fn vector_7();
    fn vector_8();
    fn vector_9();
    fn vector_10();
    fn vector_11();
    fn vector_12();
    fn vector_13();
    fn vector_14();
    fn vector_15();
    fn vector_16();
    fn vector_17();
    fn vector_18();
    fn vector_19();
    fn vector_20();
    fn vector_21();
    fn vector_22();
    fn vector_23();
    fn vector_24();
    fn vector_25();
    fn vector_26();
    fn vector_27();
    fn vector_28();
    fn vector_29();
    fn vector_30();
    fn vector_31();
}

/// Initialize the IDT with the early exception handlers.
///
/// # Safety
///
/// Must be called once on the BSP after the GDT is loaded.
#[allow(unsafe_code)]
pub unsafe fn init() {
    // SAFETY: `idt::set_handler` writes only within the static IDT array.
    unsafe {
        idt::set_handler(0, vector_0 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(1, vector_1 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(2, vector_2 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(3, vector_3 as *const () as u64, 0, IDT_TRAP_GATE);
        idt::set_handler(4, vector_4 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(5, vector_5 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(6, vector_6 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(7, vector_7 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(8, vector_8 as *const () as u64, 1, IDT_INTERRUPT_GATE);
        idt::set_handler(9, vector_9 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(10, vector_10 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(11, vector_11 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(12, vector_12 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(13, vector_13 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(14, vector_14 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(15, vector_15 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(16, vector_16 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(17, vector_17 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(18, vector_18 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(19, vector_19 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(20, vector_20 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(21, vector_21 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(22, vector_22 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(23, vector_23 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(24, vector_24 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(25, vector_25 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(26, vector_26 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(27, vector_27 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(28, vector_28 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(29, vector_29 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(30, vector_30 as *const () as u64, 0, IDT_INTERRUPT_GATE);
        idt::set_handler(31, vector_31 as *const () as u64, 0, IDT_INTERRUPT_GATE);
    }
}

/// Rust dispatch function called from the assembly entry stubs.
///
/// # Safety
///
/// `frame` must point to a valid `ExceptionFrame` built by the assembly stubs.
#[allow(unsafe_code)]
#[unsafe(no_mangle)]
extern "C" fn rust_exception_dispatch(frame: *const ExceptionFrame) {
    // SAFETY: The assembly stubs always pass a valid, aligned frame pointer.
    let frame = unsafe { &*frame };
    match frame.vector as u8 {
        VECTOR_BREAKPOINT => handle_breakpoint(frame),
        VECTOR_INVALID_OPCODE => handle_invalid_opcode(frame),
        VECTOR_DOUBLE_FAULT => handle_double_fault(frame),
        VECTOR_GENERAL_PROTECTION => handle_general_protection(frame),
        VECTOR_PAGE_FAULT => handle_page_fault(frame),
        _ => handle_unhandled(frame),
    }
}

fn handle_breakpoint(_frame: &ExceptionFrame) {
    serial::log(format_args!("FINNOS:EXCEPTION:BREAKPOINT\n"));
    #[cfg(feature = "qemu-test-exceptions")]
    {
        TEST_STATE.store(TestState::Breakpoint as u8, Ordering::SeqCst);
    }
    // Breakpoint is resumable; the assembly stub will perform iretq.
}

fn handle_invalid_opcode(frame: &ExceptionFrame) {
    serial::log(format_args!("FINNOS:EXCEPTION:INVALID_OPCODE\n"));
    #[cfg(feature = "qemu-test-exceptions")]
    {
        let state = TEST_STATE.load(Ordering::SeqCst);
        if state == TestState::InvalidOpcode as u8 {
            serial::log(format_args!("FINNOS:TEST:INVALID_OPCODE:PASS\n"));
            qemu::exit(0x10);
        }
    }
    fatal(frame, "INVALID_OPCODE");
}

fn handle_double_fault(frame: &ExceptionFrame) {
    serial::log(format_args!("FINNOS:EXCEPTION:DOUBLE_FAULT\n"));
    fatal(frame, "DOUBLE_FAULT");
}

fn handle_general_protection(frame: &ExceptionFrame) {
    serial::log(format_args!("FINNOS:EXCEPTION:GENERAL_PROTECTION\n"));
    fatal(frame, "GENERAL_PROTECTION");
}

fn handle_page_fault(frame: &ExceptionFrame) {
    serial::log(format_args!("FINNOS:EXCEPTION:PAGE_FAULT\n"));
    // SAFETY: Reading CR2 is safe in ring 0 and returns the faulting address.
    let cr2: u64;
    unsafe {
        core::arch::asm!("mov {}, cr2", out(reg) cr2, options(nomem, nostack, preserves_flags));
    }
    serial::log(format_args!(
        "CR2={:#018x} ERROR={:#018x}\n",
        cr2, frame.error_code
    ));
    fatal(frame, "PAGE_FAULT");
}

fn handle_unhandled(frame: &ExceptionFrame) {
    serial::log(format_args!("FINNOS:EXCEPTION:UNHANDLED\n"));
    fatal(frame, "UNHANDLED");
}

/// Print fatal exception diagnostics and halt or exit QEMU.
#[allow(unsafe_code)]
fn fatal(frame: &ExceptionFrame, category: &str) {
    serial::log(format_args!("FINNOS:EXCEPTION:FATAL\n"));
    serial::log(format_args!(
        "VECTOR={:#04x} ERROR={:#018x} RIP={:#018x} CS={:#06x} RFLAGS={:#018x}\n",
        frame.vector, frame.error_code, frame.rip, frame.cs, frame.rflags
    ));
    serial::log(format_args!("CATEGORY={}\n", category));
    // SAFETY: Fatal exceptions must not return; disabling interrupts prevents an errant
    // interrupt from resuming execution after the final halt.
    unsafe {
        core::arch::asm!("cli", options(nomem, nostack, preserves_flags));
    }
    qemu::exit(0x11);
}

/// Initialize descriptor tables and exception handlers.
///
/// # Safety
///
/// Must be called once on the BSP with interrupts disabled.
#[allow(unsafe_code)]
pub unsafe fn init_exception_foundation(rsp0: u64) {
    // `EXCEPTION_TSS` is a static mutable accessed only during single-core init.
    let tss = &raw mut EXCEPTION_TSS;
    unsafe {
        super::tss::init(&mut *tss, rsp0);
    }
    serial::log(format_args!("FINNOS:KERNEL:TSS_INIT\n"));
    // SAFETY: `gdt::init` loads the GDT with a valid TSS descriptor.
    unsafe {
        super::gdt::init(&*tss);
        serial::log(format_args!("FINNOS:KERNEL:GDT_LOADED\n"));
        super::gdt::reload_segments();
        serial::log(format_args!("FINNOS:KERNEL:SEGMENTS_RELOADED\n"));
        super::gdt::load_task_register();
    }
    serial::log(format_args!("FINNOS:KERNEL:GDT_OK\n"));
    serial::log(format_args!("FINNOS:KERNEL:TSS_OK\n"));

    // SAFETY: `exceptions::init` installs handlers into the static IDT.
    unsafe {
        init();
        idt::load();
    }
    serial::log(format_args!("FINNOS:KERNEL:IDT_OK\n"));
    serial::log(format_args!("FINNOS:KERNEL:EXCEPTIONS_READY\n"));
}

/// Run the controlled exception test sequence.
///
/// # Safety
///
/// Must be called after `init_exception_foundation` with the IDT loaded.
#[allow(unsafe_code)]
pub unsafe fn run_exception_tests() {
    serial::log(format_args!("FINNOS:TEST:EXCEPTIONS:BEGIN\n"));

    serial::log(format_args!("FINNOS:TEST:BREAKPOINT:BEGIN\n"));
    TEST_STATE.store(TestState::Breakpoint as u8, Ordering::SeqCst);
    // SAFETY: `int3` is a controlled breakpoint in the test feature.
    unsafe {
        core::arch::asm!("int3", options(nomem, nostack));
    }
    serial::log(format_args!("FINNOS:TEST:BREAKPOINT:PASS\n"));

    serial::log(format_args!("FINNOS:TEST:INVALID_OPCODE:BEGIN\n"));
    TEST_STATE.store(TestState::InvalidOpcode as u8, Ordering::SeqCst);
    // SAFETY: `ud2` is a controlled invalid-opcode in the test feature.
    unsafe {
        core::arch::asm!("ud2", options(nomem, nostack));
    }
    // `ud2` should not return; if it does, the test failed.
    fatal(
        &ExceptionFrame {
            rax: 0,
            rbx: 0,
            rcx: 0,
            rdx: 0,
            rsi: 0,
            rdi: 0,
            rbp: 0,
            r8: 0,
            r9: 0,
            r10: 0,
            r11: 0,
            r12: 0,
            r13: 0,
            r14: 0,
            r15: 0,
            vector: 0,
            error_code: 0,
            rip: 0,
            cs: 0,
            rflags: 0,
        },
        "INVALID_OPCODE_DID_NOT_FAULT",
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use core::mem::offset_of;

    #[test]
    fn error_code_vectors_include_double_fault() {
        assert!(ERROR_CODE_VECTORS.contains(&VECTOR_DOUBLE_FAULT));
        assert!(ERROR_CODE_VECTORS.contains(&VECTOR_GENERAL_PROTECTION));
        assert!(ERROR_CODE_VECTORS.contains(&VECTOR_PAGE_FAULT));
    }

    #[test]
    fn breakpoint_vector_has_no_error_code() {
        assert!(!ERROR_CODE_VECTORS.contains(&VECTOR_BREAKPOINT));
    }

    #[test]
    fn invalid_opcode_vector_has_no_error_code() {
        assert!(!ERROR_CODE_VECTORS.contains(&VECTOR_INVALID_OPCODE));
    }

    #[test]
    fn exception_frame_layout_matches_push_order() {
        // The assembly stub pushes rax first (lowest address) and r15 last (highest address among
        // the saved general-purpose registers), then vector, error_code, rip, cs, rflags.
        assert_eq!(offset_of!(ExceptionFrame, rax), 0);
        assert_eq!(offset_of!(ExceptionFrame, rbx), 8);
        assert_eq!(offset_of!(ExceptionFrame, rbp), 8 * 6);
        assert_eq!(offset_of!(ExceptionFrame, r15), 8 * 14);
        assert_eq!(offset_of!(ExceptionFrame, vector), 8 * 15);
        assert_eq!(offset_of!(ExceptionFrame, error_code), 8 * 16);
        assert_eq!(offset_of!(ExceptionFrame, rip), 8 * 17);
        assert_eq!(offset_of!(ExceptionFrame, cs), 8 * 18);
        assert_eq!(offset_of!(ExceptionFrame, rflags), 8 * 19);
        assert_eq!(core::mem::size_of::<ExceptionFrame>(), 8 * 20);
    }

    #[test]
    fn breakpoint_and_invalid_opcode_have_synthetic_zero_error_code() {
        assert!(!ERROR_CODE_VECTORS.contains(&VECTOR_BREAKPOINT));
        assert!(!ERROR_CODE_VECTORS.contains(&VECTOR_INVALID_OPCODE));
    }
}
